import {
  BadRequestException,
  Injectable,
  Logger,
  NotFoundException,
} from '@nestjs/common';
import { Prisma } from '@prisma/client';
import { PrismaService } from '../../database/prisma.service';
import { AiModelService } from '../ai/ai.model.service';
import { FaqParserService } from './faq-parser.service';
import { GmailProvider } from '../email/gmail/gmail-provider.service';

/** Threshold for a vector match to be treated as "this FAQ answers the email". */
export const FAQ_SIMILARITY_THRESHOLD = process.env.FAQ_SIMILARITY_THRESHOLD
  ? parseFloat(process.env.FAQ_SIMILARITY_THRESHOLD)
  : 0.65;

/** How many FAQ items can exist per tenant. Guards against accidental bulk import. */
const MAX_FAQ_ITEMS_PER_TENANT = 500;

export interface FaqMatchResult {
  faqItemId: string;
  question: string;
  answer: string;
  similarity: number;
}

export interface TryAutoReplyParams {
  tenantId: string;
  accountEmail: string;
  messageId: string;
  threadId: string | null;
  subject: string;
  clientEmail: string;
  emailText: string;
  isFaq: boolean;
  faqConfidence: number;
  isComplaint: boolean;
  intent: string;
  analysisId: string;
}

@Injectable()
export class FaqService {
  private readonly logger = new Logger(FaqService.name);

  constructor(
    private readonly prisma: PrismaService,
    private readonly aiModelService: AiModelService,
    private readonly parser: FaqParserService,
    private readonly gmailProvider: GmailProvider,
  ) {}

  /**
   * Attempts to auto-reply to an email if:
   * 1. Classifier flagged it as FAQ-shaped (isFaq=true, faqConfidence >= 0.7, non-complaint, non-sensitive).
   * 2. No auto-reply has been sent in this thread within the last 60 minutes.
   * 3. A vector search match is found above FAQ_SIMILARITY_THRESHOLD (0.75).
   */
  async tryAutoReply(params: TryAutoReplyParams): Promise<boolean> {
    const {
      tenantId,
      accountEmail,
      messageId,
      threadId,
      subject,
      clientEmail,
      emailText,
      isFaq,
      faqConfidence,
      isComplaint,
      intent,
      analysisId,
    } = params;

    if (
      !isFaq ||
      faqConfidence < 0.7 ||
      isComplaint ||
      intent === 'sensitive' ||
      !threadId
    ) {
      return false;
    }

    const windowStart = new Date(Date.now() - 60 * 60 * 1000);
    const recentAutoReply = await this.prisma.generalAnalysis.findFirst({
      where: {
        threadId,
        tenantId,
        faqAutoReplied: true,
        createdAt: { gte: windowStart },
      },
      select: { id: true },
    });

    if (recentAutoReply) {
      this.logger.debug(
        `FAQ auto-reply skipped for thread ${threadId}: already auto-replied within the last 60 minutes`,
      );
      return false;
    }

    try {
      const match = await this.findBestMatch(tenantId, emailText);
      if (!match) return false;

      const replyBody = [
        `Hi,`,
        ``,
        match.answer,
        ``,
        `Best regards,`,
        accountEmail,
        ``,
        `---`,
        `[Automated Reply] This is an automated response generated by SalesBox AI Assistant based on our company FAQ.`,
      ].join('\n');

      const sentMessageId = await this.gmailProvider.sendReply(
        tenantId,
        accountEmail,
        messageId,
        threadId,
        clientEmail,
        subject ?? '',
        replyBody,
      );

      await this.prisma.generalAnalysis.update({
        where: { id: analysisId },
        data: {
          faqAutoReplied: true,
          faqItemId: match.faqItemId,
        },
      });

      this.logger.log(
        `FAQ auto-reply sent for message ${messageId} ` +
          `(tenant ${tenantId}, sent as ${sentMessageId}, ` +
          `FAQ item ${match.faqItemId}, similarity ${match.similarity.toFixed(3)})`,
      );
      return true;
    } catch (faqError) {
      this.logger.error(
        `FAQ auto-reply failed for message ${messageId}: ` +
          `${faqError instanceof Error ? faqError.message : String(faqError)}.`,
      );
      return false;
    }
  }

  /**
   * Parses a FAQ file, stores items, and embeds questions asynchronously.
   * Replaces any existing document with the same filename for this tenant.
   */
  async ingest(
    tenantId: string,
    filename: string,
    buffer: Buffer,
    uploadedBy?: string,
  ): Promise<{ filename: string; itemsCreated: number }> {
    const pairs = await this.parser.parse(filename, buffer);
    if (pairs.length === 0) {
      throw new BadRequestException(
        'No Q&A pairs could be parsed from the uploaded file. Check the format.',
      );
    }

    // Cap before storing — a 10,000-row FAQ upload is almost certainly a mistake.
    const existing = await this.prisma.faqItem.count({
      where: { tenantId },
    });
    if (existing + pairs.length > MAX_FAQ_ITEMS_PER_TENANT) {
      throw new BadRequestException(
        `Adding ${pairs.length} items would exceed the ${MAX_FAQ_ITEMS_PER_TENANT} FAQ item limit for this tenant (currently ${existing}).`,
      );
    }

    return this.prisma.$transaction(async (tx) => {
      // Serialise concurrent uploads of the same filename.
      const lockKey = `${tenantId}:faq:${filename}`;
      await tx.$executeRaw`SELECT pg_advisory_xact_lock(hashtextextended(${lockKey}, 0))`;

      // Delete any previous version of this file.
      await tx.faqDocument.deleteMany({
        where: { tenantId, filename },
      });

      const doc = await tx.faqDocument.create({
        data: {
          tenantId,
          filename,
          uploadedBy,
          items: {
            create: pairs.map((p) => ({
              tenantId,
              question: p.question,
              answer: p.answer,
              // embedding is null — filled by embedFaqItems() below
            })),
          },
        },
        include: { items: { select: { id: true } } },
      });

      this.logger.log(
        `FAQ ingest: tenant ${tenantId} — ${doc.items.length} items from "${filename}"`,
      );

      // Embed questions synchronously before returning.
      const itemIds = doc.items.map((i) => i.id);
      await this.embedFaqItems(itemIds);

      return { filename, itemsCreated: doc.items.length };
    });
  }

  /**
   * Embeds all questions for the given item ids.
   * Called fire-and-forget from ingest; also called by any future backfill.
   */
  async embedFaqItems(itemIds: string[]): Promise<void> {
    if (itemIds.length === 0) return;

    const items = await this.prisma.faqItem.findMany({
      where: { id: { in: itemIds } },
      select: { id: true, question: true },
    });

    const texts = items.map((i) => i.question);
    let vectors: number[][];
    try {
      vectors = await this.aiModelService.embedDocuments(texts);
    } catch (err) {
      this.logger.error(
        `FAQ embedding failed for ${items.length} items: ${err instanceof Error ? err.message : String(err)}`,
      );
      return;
    }

    for (let i = 0; i < items.length; i++) {
      await this.prisma.$executeRaw`
        UPDATE faq_items
        SET embedding = ${JSON.stringify(vectors[i])}::vector
        WHERE id = ${items[i].id}::uuid
      `;
    }
    this.logger.log(`Embedded ${items.length} FAQ questions`);
  }

  /**
   * Finds the best-matching FAQ item for a given email text.
   *
   * Embeds the query text, does a cosine similarity search against all of this
   * tenant's FAQ item embeddings, and returns the top result if it scores above
   * FAQ_SIMILARITY_THRESHOLD. Returns null when nothing is close enough or when
   * no embedded FAQ items exist yet.
   */
  async findBestMatch(
    tenantId: string,
    queryText: string,
  ): Promise<FaqMatchResult | null> {
    const queryVector = await this.aiModelService.embedQuery(queryText);
    const vectorLiteral = JSON.stringify(queryVector);

    type Row = {
      id: string;
      question: string;
      answer: string;
      similarity: number;
    };

    const rows = await this.prisma.$queryRaw<Row[]>(Prisma.sql`
      SELECT id,
             question,
             answer,
             1 - (embedding <=> ${vectorLiteral}::vector) AS similarity
      FROM faq_items
      WHERE tenant_id = ${tenantId}::uuid
        AND embedding IS NOT NULL
      ORDER BY embedding <=> ${vectorLiteral}::vector
      LIMIT 1
    `);

    if (rows.length === 0) return null;
    const best = rows[0];

    if (best.similarity < FAQ_SIMILARITY_THRESHOLD) {
      this.logger.debug(
        `FAQ: best match similarity ${best.similarity.toFixed(3)} below threshold ${FAQ_SIMILARITY_THRESHOLD}; no auto-reply`,
      );
      return null;
    }

    this.logger.log(
      `FAQ match: similarity ${best.similarity.toFixed(3)} for item ${best.id} (tenant ${tenantId})`,
    );
    return {
      faqItemId: best.id,
      question: best.question,
      answer: best.answer,
      similarity: best.similarity,
    };
  }

  /** Paginated list of FAQ items for the admin panel. */
  async listItems(
    tenantId: string,
    page = 1,
    limit = 50,
  ): Promise<{
    data: { id: string; question: string; answer: string; embedded: boolean }[];
    meta: { total: number; page: number; limit: number; totalPages: number };
  }> {
    const skip = (page - 1) * limit;
    const [items, total] = await Promise.all([
      this.prisma.$queryRaw<
        { id: string; question: string; answer: string; embedded: boolean }[]
      >`
        SELECT id,
               question,
               answer,
               embedding IS NOT NULL AS embedded
        FROM faq_items
        WHERE tenant_id = ${tenantId}::uuid
        ORDER BY created_at DESC
        LIMIT ${limit} OFFSET ${skip}
      `,
      this.prisma.faqItem.count({ where: { tenantId } }),
    ]);

    return {
      data: items,
      meta: { total, page, limit, totalPages: Math.ceil(total / limit) },
    };
  }

  /** Lists all FAQ documents (not their items) for the admin panel. */
  listDocuments(tenantId: string) {
    return this.prisma.faqDocument.findMany({
      where: { tenantId },
      select: {
        id: true,
        filename: true,
        uploadedBy: true,
        uploadedAt: true,
        _count: { select: { items: true } },
      },
      orderBy: { uploadedAt: 'desc' },
    });
  }

  /** Deletes a single FAQ item (tenant-scoped). */
  async deleteItem(tenantId: string, itemId: string): Promise<void> {
    const { count } = await this.prisma.faqItem.deleteMany({
      where: { id: itemId, tenantId },
    });
    if (count === 0)
      throw new NotFoundException(`FAQ item ${itemId} not found`);
  }

  /** Deletes an entire FAQ document and all its items (tenant-scoped). */
  async deleteDocument(tenantId: string, documentId: string): Promise<void> {
    const { count } = await this.prisma.faqDocument.deleteMany({
      where: { id: documentId, tenantId },
    });
    if (count === 0)
      throw new NotFoundException(`FAQ document ${documentId} not found`);
  }

  /** Deletes ALL FAQ items for a tenant. */
  async deleteAll(tenantId: string): Promise<{ deleted: number }> {
    const { count } = await this.prisma.faqDocument.deleteMany({
      where: { tenantId },
    });
    this.logger.warn(
      `FAQ cleared for tenant ${tenantId} — ${count} document(s) removed`,
    );
    return { deleted: count };
  }
}
